### ISSUE TITLE
New version / dependency issue

### ISSUE THREAD

**Issue by MHRosenberg** [alen-smajic/Stable-Diffusion-Latent-Space-Explorer#2]
Hi there,

I've been using your code off-and-on for a few weeks. I'm hitting a new dependency error presumably due to changes in the underlying packages. Do you current get this error below? If not, could you send a complete list of the versions associated with the dependencies?

Traceback (most recent call last):
  File "/content/drive/MyDrive/creative/Stable-Diffusion-Latent-Space-Explorer/run_sd_experiment.py", line 7, in <module>
    import models
  File "/content/drive/MyDrive/creative/Stable-Diffusion-Latent-Space-Explorer/models.py", line 5, in <module>
    from torchvision import transforms
  File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 4, in <module>
    import torch._custom_ops
ModuleNotFoundError: No module named 'torch._custom_ops'

Thanks!

**Comment by alen-smajic** [comment]
Hello,

what torch, torchvision and CUDA version are you using?
Back then when I worked on the code, I used torch 2.0.0, torchvision 0.15.1 and CUDA 11.8

If your CUDA version matches you can install the rest via:
pip install torch==2.0.0 torchvision==0.15.1 --index-url https://download.pytorch.org/whl/cu118
